#ifndef CONSTANTS_H
#define CONSTANTS_H

#define STARTING_WINDOW_WIDTH 1920
#define STARTING_WINDOW_HEIGHT 1080

#define MAXIMUM_PARTICLE_TYPES 100
#define MAXIMUM_PARTICLES 100000
#define CONFIG_MATRIX_CELL_WIDTH 50
#define CONFIG_MATRIX_CELL_HEIGHT 50
#endif